### ISSUE TITLE
Order not save in magento backend using this payment method

### ISSUE THREAD

**Issue by zoya-d** [GetFinancing/getfinancing-magento#1]
hello , 
 Using this payment method order data save in getfinancing platform but this order is not save in magento backend admin also this order not available in magento db

**Comment by sindreu** [comment]
Are you using the latest release (1.0.4)? That release fixed some issues
with the postbacks. What site are you using it on?

**Comment by sindreu** [comment]
This was fixed. It was due to an error with an existing 3rd party module actually.
